packages:
  - .
  - playground
catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.4
    tsdown: ^0.20.3
    unplugin-icons: ^23.0.1
    unplugin-lightningcss: ^0.4.5
    vite: ^7.3.1
  dev:
    bumpp: ^10.4.1
    happy-dom: ^20.6.3
    pncat: ^0.10.2
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
  lint:
    '@octohash/eslint-config': ^0.2.3
    eslint: ^10.0.0
    eslint-plugin-format: ^1.4.0
    lint-staged: ^16.2.7
    vue-tsc: ^3.2.4
  test:
    '@vue/test-utils': ^2.4.6
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
